execute: 
  cache: false
  freeze: auto
  message: false
  warning: false

project:
  render: 
    - "code/*.qmd"
    - "!code/csama.qmd"
    - "!code/4d.qmd"
    - "!code/fractal.qmd"
    - "!code/visium.qmd"
    - "!code/visiumhd.qmd"
    - "!code/xenium.qmd"
  type: website
  output-dir: docs
  execute-dir: project

format:
  html:
    toc: true
    toc-depth: 4
    code-fold: false
    standalone: true
    embed-resources: true
    bibliography: code/_.bib

website:
  title: "SpatialData"
  navbar:
    left:
      - code/csama.qmd
      - code/fractal.qmd
      - code/merfish.qmd
      - code/mibitof.qmd
      - code/mcmicro.qmd
      - code/cosmx.qmd
      - code/xenium.qmd
      - code/visium.qmd
      - code/visiumhd.qmd
