---
title: MIBITOF
author:
  - name: Helena L Crowell
    affiliation: CNAG, Barcelona, Spain
date: last-modified
---

### preamble

```{r load-libs}
library(sf)
library(dplyr)
library(ggplot2)
library(patchwork)
library(spatialdataR)
library(SpatialData.data)
library(SpatialData.plot)
```

```{r load-data}
(sd <- SD.data_load("ColorectalCarcinomaMIBITOF"))
```

### analysis

```{r fig.width=9, fig.height=3.5}
cl <- rep(list(c(0, 1/3)), 3) # contrast limits
ps <- lapply(imageNames(sd), \(i) plotSpatialData() + plotImage(x=sd, i=i, cl=cl) + ggtitle(i))
wrap_plots(ps, nrow=1) & theme(legend.position="none")
```

```{r fig.width=8, fig.height=3, message=FALSE}
bb <- list(xmin=0, xmax=800, ymin=200, ymax=500)
(sp <- crop(sd, bb, j="point23"))
plotSpatialData() + plotImage(x=sp, cl=cl)
```

```{r}
(se <- element(sd, "table"))
base::table(ks <- se$Cluster)
```

```{r fig.width=10, fig.height=3.5}
is <- labelNames(sd)
ps <- lapply(is, \(i) 
    plotSpatialData() + 
        ggtitle(i) + 
        plotLabel(x=sd, i=i, a=2/3,
            c="Cluster", na="black", 
            pal=rainbow(nlevels(ks))))
wrap_plots(ps, nrow=1, guides="collect")
```

```{r}
sp <- query(sd, i="table", grepl("Tc", Cluster))
base::table(table(sp)$Cluster)
```

```{r fig.width=10, fig.height=3.5}
# TODO: this is wrong!
is <- labelNames(sd)
ps <- lapply(is, \(i) 
    plotSpatialData() + 
        ggtitle(i) + 
        plotLabel(x=sp, i=i, a=2/3,
            c="Cluster", na="black", 
            pal=c("gold", "blue")))
wrap_plots(ps, nrow=1, guides="collect")
```

### appendix

::: {.callout-note icon=false, collapse=true}

### session

```{r sess-info}
sessionInfo()
```

:::
