name: Build and Render Quarto Website

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - devel
  push:
    branches:
      - main
      - devel
  schedule:
    - cron: '0 8 * * 1'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Cache downloaded datasets
      uses: actions/cache@v6
      with:
        path: ~/.cache/R/BiocFileCache
        key: ${{ runner.os }}-${{ github.ref_name }}-cached-data
        restore-keys: |
          ${{ runner.os }}-${{ github.event.pull_request.base.ref }}-cached-data

    - name: Cache `_freeze` folder
      uses: actions/cache@v6
      with:
        path: _freeze
        key: ${{ runner.os }}-${{ github.ref_name }}-freeze
        restore-keys: |
          ${{ runner.os }}-${{ github.event.pull_request.base.ref }}-freeze

    - uses: quarto-dev/quarto-actions/setup@v2

    - uses: r-lib/actions/setup-r@v2

    - uses: r-lib/actions/setup-pandoc@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y cmake gdal-bin gsfonts \
          libabsl-dev libcurl4-openssl-dev libfftw3-dev libfontconfig1-dev \
          libfreetype6-dev libgdal-dev libgeos-dev libicu-dev libjpeg-dev \
          libmagick++-dev libpng-dev libproj-dev libsqlite3-dev libssl-dev \
          libtiff-dev libudunits2-dev libuv1-dev libxml2-dev libzstd-dev make \
          python3 xz-utils

    - uses: r-lib/actions/setup-renv@v2

    - uses: quarto-dev/quarto-actions/render@v2
      env:
        # Required by SpatialData.data. Report as a bug?
        AWS_REGION: us-east-1

    - uses: quarto-dev/quarto-actions/publish@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        target: gh-pages
